package vista;

import Archivo.Archivo;
import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class MenuCategorias extends javax.swing.JFrame {
    private static final String NOMBRE_ARCHIVO = "DatosProductos.txt";
    /**
     * Creates new form MenuCategorias
     */
    public MenuCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        bHamburguesas = new javax.swing.JButton();
        bBroasters = new javax.swing.JButton();
        bSalchipapas = new javax.swing.JButton();
        bAlitas = new javax.swing.JButton();
        bCombos = new javax.swing.JButton();
        bBebidas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bHamburguesas.setText(" Hamburguesas");
        bHamburguesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHamburguesasActionPerformed(evt);
            }
        });

        bBroasters.setText("Broasters");
        bBroasters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBroastersActionPerformed(evt);
            }
        });

        bSalchipapas.setText("Salchipapas");
        bSalchipapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalchipapasActionPerformed(evt);
            }
        });

        bAlitas.setText("Alitas");
        bAlitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlitasActionPerformed(evt);
            }
        });

        bCombos.setText("Combos");
        bCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCombosActionPerformed(evt);
            }
        });

        bBebidas.setText("Bebidas");
        bBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBebidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(bBroasters)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bHamburguesas))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(bSalchipapas)
                                                .addGap(47, 47, 47)
                                                .addComponent(bCombos)
                                                .addGap(0, 19, Short.MAX_VALUE)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(bAlitas)
                                        .addComponent(bBebidas))
                                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bAlitas)
                                        .addComponent(bHamburguesas)
                                        .addComponent(bBroasters))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bSalchipapas)
                                        .addComponent(bCombos)
                                        .addComponent(bBebidas))
                                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void bHamburguesasActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Archivo archivo = new Archivo("DatosProductos.txt");

        // Crear la ventana de productos y mostrarla
        JFrame ventana = new JFrame("Productos - Hamburguesas");
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.add(new VentanaProductos("hamburguesas", archivo)); // Pasa la categoría y el objeto Archivo
        ventana.setSize(400, 400);
        ventana.setVisible(true);
    }

    private void bBroastersActionPerformed(java.awt.event.ActionEvent evt) {
        Archivo archivo = new Archivo("DatosProductos.txt");

        // Crear la ventana de productos y mostrarla
        JFrame ventana = new JFrame("Productos - Broasters");
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.add(new VentanaProductos("Hamburguesas", archivo)); // Pasa la categoría y el objeto Archivo
        ventana.setSize(400, 400);
        ventana.setVisible(true);

        // TODO add your handling code here:
    }

    private void bSalchipapasActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Archivo archivo = new Archivo("DatosProductos.txt");

        // Crear la ventana de productos y mostrarla
        JFrame ventana = new JFrame("Productos - Salchipapas");
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.add(new VentanaProductos("Salchipapas", archivo)); // Pasa la categoría y el objeto Archivo
        ventana.setSize(400, 400);
        ventana.setVisible(true);

    }

    private void bAlitasActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Archivo archivo = new Archivo("DatosProductos.txt");

        // Crear la ventana de productos y mostrarla
        JFrame ventana = new JFrame("Productos - Alitas");
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.add(new VentanaProductos("Alitas", archivo)); // Pasa la categoría y el objeto Archivo
        ventana.setSize(400, 400);
        ventana.setVisible(true);
    }

    private void bCombosActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Archivo archivo = new Archivo("DatosProductos.txt");

        // Crear la ventana de productos y mostrarla
        JFrame ventana = new JFrame("Productos - Combos");
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.add(new VentanaProductos("Combos", archivo)); // Pasa la categoría y el objeto Archivo
        ventana.setSize(400, 400);
        ventana.setVisible(true);
    }

    private void bBebidasActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Archivo archivo = new Archivo("DatosProductos.txt");

        // Crear la ventana de productos y mostrarla
        JFrame ventana = new JFrame("Productos - Bebidas");
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.add(new VentanaProductos("Bebidas", archivo)); // Pasa la categoría y el objeto Archivo
        ventana.setSize(400, 400);
        ventana.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton bAlitas;
    private javax.swing.JButton bBebidas;
    private javax.swing.JButton bBroasters;
    private javax.swing.JButton bCombos;
    private javax.swing.JButton bHamburguesas;
    private javax.swing.JButton bSalchipapas;
    // End of variables declaration
}
